#! /bin/bash

echo ""
echo "-. .-.   .-. .-.   .-. .-.   ."
echo "||\|||\ /|||\|||\ /|||\|||\ /|"
echo "|/ \|||\|||/ \|||\|||/ \|||\||"
echo "~   ·-~ ·-·   ·-~ ·-·   -~  ·~"



echo ""
echo -e "\033[1mChipNChop\033[0m is a straight-forward bash script that performs ChIP-seq data analysis. For this purpose, it takes an TXT dataset including parameters detailed in the README document."
echo ""

## The next message will appear if no imputs are given.

if [ $# -ne 1 ]
then
        echo "Usage: bash chipnchop.sh <params>"
        echo ""
        echo "params: Input file including the parameters"
        exit
fi

## In any other case, the script will print the experiment name and number of
## samples specified in the parameters file.


echo ""
echo "============================"
echo "|    Reading parameters    |"
echo "============================"
echo ""

PARAMS=$1

WD=$(grep working_directory: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mWorking directory\e[0m: $WD"

EXP=$(grep experiment_name $PARAMS | awk '{ print $2 }')
echo -e "\e[4mExperiment name\e[0m: $EXP"

NSAM=$(grep number_samples: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mNumber of samples\e[0m: $NSAM"

GEND=$(grep genome_directory: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mGenome directory\e[0m: $GEND"

ANND=$(grep annotation_directory: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mAnnotation directory\e[0m: $ANND"


## INSDIR=$(grep installation_directory: $PARAMS | awk '{ print $2 }')
## echo -e "\e[4mInstallation directory\e[0m: $INSDIR"

## DESIGN=$(grep experimental_design: $PARAMS | awk '{ print $2 }')
## echo -e "\e[4mExperimental design directory\e[0m: $DESIGN"

i=0
j=1
SAMPLES=()

while [ $i -le $NSAM ]
do
        SAMPLES[$i]=$(grep path_sample_$j: $PARAMS | awk '{ print $2 }')
        ((j++))
        ((i++))
done

echo -e "\e[4mSamples directory\e[0m = ${SAMPLES[@]}"

## Once these parameters have been read, workspace is set:

echo ""
echo "============================"
echo "|    Creating workspace    |"
echo "============================"
echo ""

cd $WD
mkdir $EXP
cd $EXP
mkdir genome annotation samples results

cd genome
cp $GEND genome.fa

cd ../annotation
cp $ANND annotation.gtf

## Generating reference genome index
extract_splice_sites.py annotation.gtf > annot_splice.ss
extract_exons.py annotation.gtf > annot_exons.exon

echo ""
echo "Genome indexing may take a while. Please be patient."
echo ""

cd ../genome
hisat2-build --ss ../annotation/annot_splice.ss --exon ../annotation/annot_exons.exon genome.fa index

echo ""
echo "Index done"
echo ""

## Copying sample data to their corresponding sample file

cd ../samples

i=1
while [ $i -le $NSAM ]
do
	mkdir sample_$i
	cd sample_$i
	cp ${SAMPLES[1]} sample_$i.fq.gz
	cd ../
	((i++))
done

## Let's move on to the sample analysis. This will take a while, as
## datasets are heavy.





exit






echo ""
echo "============================"
echo "|     Sample analysis      |"
echo "============================"
echo ""
echo "Individual samples are being processed."

cd ../results

i=1
while [ $i -le $NSAM ]
do
	qsub -o sample_$i -N sample_$i ${INSDIR}/ARNeatSequences/rnaseq_sample_processing $WD/$EXP/samples/sample_$i $i $NSAM $INSDIR $DESIGN
	((++i))
done
