#! /bin/bash

echo ""
echo "-. .-.   .-. .-.   .-. .-.   ."
echo "||\|||\ /|||\|||\ /|||\|||\ /|"
echo "|/ \|||\|||/ \|||\|||/ \|||\||"
echo "~   ·-~ ·-·   ·-~ ·-·   -~  ·~"



echo ""
echo -e "\033[1mChipNChop\033[0m is a straight-forward bash script that performs ChIP-seq data analysis for Arabidopsis thaliana. For this purpose, it takes an TXT dataset including parameters detailed in the README document."
echo ""

## The next message will appear if no imputs are given.

if [ $# -lt 1 -o $# -gt 2 ]
then
        echo "Usage: bash chipnchop.sh <params> [options]"
        echo ""
        echo "params		Input file including the parameters. Check documentation"
        echo "		in order to create an acceptable parameters file."
        echo ""
        echo "options"
        echo "-TF		This option must be specified if the analyzed proteins"
        echo "		are transcription factors or interact in a similar way."
        echo "		If not specified, this option is DEFAULT."
        echo "-HI		This option must be specified if the analyzed proteins"
        echo "		are	histones or other specific epigenetics marks that"
        echo " 		affect large portions of DNA, in contrast to transcription factors."
        
        exit
fi

## In any other case, the script will print the experiment name and number of
## samples specified in the parameters file.


echo ""
echo "============================"
echo "|    Reading parameters    |"
echo "============================"
echo ""

PARAMS=$1

WD=$(grep working_directory: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mWorking directory\e[0m: $WD"

EXP=$(grep experiment_name $PARAMS | awk '{ print $2 }')
echo -e "\e[4mExperiment name\e[0m: $EXP"

GEND=$(grep genome_directory: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mGenome directory\e[0m: $GEND"

ANND=$(grep annotation_directory: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mAnnotation directory\e[0m: $ANND"

INSDIR=$(grep installation_directory: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mInstallation directory\e[0m: $INSDIR"

CHIP=$(grep path_chip: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mChip sample directory\e[0m = ${CHIP}"

INPUT=$(grep path_input: $PARAMS | awk '{ print $2 }')
echo -e "\e[4mInput sample directory\e[0m = ${INPUT}"

MODE=$2

if [ $# -eq 1 ]; then
MODE=-TF
fi

if [[ $MODE != -TF && $MODE != -HI ]]; then
echo ""
echo -e "Invalid protein type. Write -TF or -HI as the second parameter you introduce."
echo ""
exit
fi

if [[ $MODE == -TF ]]; then
echo ""
echo -e "\e[4mProtein type\e[0m = Transcription factor (-TF)"
echo ""
fi

if [[ $MODE == -HI ]]; then
echo ""
echo -e "\e[4mProtein type\e[0m = Histone/epigenetic mark (-HI)"
echo ""
fi

## Once these parameters have been read, workspace is set:

echo ""
echo "============================"
echo "|    Creating workspace    |"
echo "============================"
echo ""

cd $WD
mkdir $EXP
cd $EXP
mkdir genome annotation samples results

cd genome
cp $GEND genome.fa

cd ../annotation
cp $ANND annotation.gtf


## Copying sample data to their corresponding sample file

cd ../samples
mkdir chip input

cd chip
cp ${CHIP} chip.fq.gz

cd ../input
cp ${INPUT} input.fq.gz

echo "Workspace succesfully created"

echo ""
echo "============================="
echo "|   Reads quality control   |"
echo "============================="
echo ""

cd $WD/$EXP/samples/chip
fastqc chip.fq.gz

cd $WD/$EXP/samples/input
fastqc input.fq.gz

echo ""
echo "============================"
echo "|      Mapping reads       |"
echo "============================"
echo ""
echo "Indexing the genome. This may take a while..."
echo ""

cd $WD/$EXP/genome
bowtie2-build $GEND index

echo ""
echo "Mapping reads to the reference genome."
echo ""

cd ../samples/chip
bowtie2 -x ../../genome/index -U $CHIP -S chip.sam

samtools sort -o chip.bam chip.sam
samtools index chip.bam

rm -r *.sam

cd ../input
bowtie2 -x ../../genome/index -U $INPUT -S input.sam

samtools sort -o input.bam input.sam
samtools index input.bam

rm -r *.sam

echo ""
echo "============================"
echo "|      Peaks calling       |"
echo "============================"
echo ""

cd $WD/$EXP/results

macs2 callpeak -t ../samples/chip/chip.bam -c ../samples/input/input.bam -f BAM --outdir . -n $EXP


if [[ $MODE == -TF ]]; then

macs2 callpeak -t ../samples/chip/chip.bam -c ../samples/input/input.bam -f BAM --outdir . -n $EXP --narrow

fi

if [[ $MODE == -HI ]]; then

macs2 callpeak -t ../samples/chip/chip.bam -c ../samples/input/input.bam -f BAM --outdir . -n $EXP --broad

fi


## R script is moved from installation directory to results

cp $INSDIR/target_genes.R .

## R script is running!

Rscript target_genes.R $WD/$EXP/results/ $EXP


echo ""
echo "============================="
echo "|      Finding motifs       |"
echo "============================="
echo ""

## Creating output directory

mkdir output_homer

findMotifsGenome.pl ${EXP}_summits.bed tair10 output_homer -len 8 -size 200

echo "Analysis is done!"
